import {
    mkdtempSync,
    mkdirSync,
    copyFileSync,
    writeFileSync,
    existsSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname, resolve } from "node:path";
import {
    dockerImageExists,
    dockerImageLabel,
    dockerPull,
    dockerBuild,
} from "./docker-client.js";
import { dockerBaseContext, moduleDir } from "./paths.js";
import {
    generateDockerLayers,
    moduleSetHash,
    type ModuleManifest,
} from "../modules/registry.js";

export const DEFAULT_BASE_IMAGE = "1claw/agent:stable";

const SAFE_BASE_IMAGE = /^[a-zA-Z0-9._/@:-]+$/;

function assertSafeBaseImage(baseImage: string): void {
    if (!SAFE_BASE_IMAGE.test(baseImage) || baseImage.includes("..")) {
        throw new Error(`Unsafe Docker base image reference: ${baseImage}`);
    }
}

function assertInside(root: string, candidate: string, label: string): string {
    const resolved = resolve(candidate);
    const rootResolved = resolve(root);
    if (resolved !== rootResolved && !resolved.startsWith(`${rootResolved}/`)) {
        throw new Error(`${label} escapes allowed directory`);
    }
    return resolved;
}

/**
 * Revision of the bundled base assets (chat UI, entrypoint, Dockerfile). Bump
 * this whenever those change so an existing `1claw/agent:stable` is rebuilt
 * instead of silently reused. Stamped into the image as a label.
 */
export const BASE_IMAGE_VERSION = "6";
const BASE_VERSION_LABEL = "org.1claw.base-version";

/** Build the base image from the bundled Docker context. */
export async function buildBaseImage(
    tag = DEFAULT_BASE_IMAGE,
    onProgress?: (line: string) => void,
): Promise<string> {
    const context = dockerBaseContext();
    const dockerfile = join(context, "Dockerfile");
    if (!existsSync(dockerfile)) {
        throw new Error(`Base Dockerfile not found at ${dockerfile}`);
    }
    return dockerBuild({
        context,
        dockerfile,
        tag,
        buildArgs: { ONECLAW_BASE_VERSION: BASE_IMAGE_VERSION },
        onProgress,
    });
}

/**
 * Ensure the base image is available locally. If it's the default 1Claw image
 * and missing (or stale — built from an older bundled-asset revision), build it
 * from bundled assets (works offline). Otherwise pull it.
 */
export async function ensureBaseImage(
    baseImage: string,
    onProgress?: (line: string) => void,
): Promise<void> {
    const exists = await dockerImageExists(baseImage);
    if (baseImage === DEFAULT_BASE_IMAGE) {
        if (exists) {
            const ver = await dockerImageLabel(baseImage, BASE_VERSION_LABEL);
            if (ver === BASE_IMAGE_VERSION) return;
            // Missing/old label → rebuild from current bundled assets.
            onProgress?.("base image is stale — rebuilding");
        }
        await buildBaseImage(baseImage, onProgress);
        return;
    }
    if (exists) return;
    await dockerPull(baseImage, onProgress);
}

/** Produce the full Dockerfile content for a base image + module layers. */
export function generateDockerfile(
    baseImage: string,
    modules: ModuleManifest[],
): string {
    assertSafeBaseImage(baseImage);
    const header =
        "# Generated by 1claw — base image + module layers.\n" +
        `FROM ${baseImage}\n`;
    if (modules.length === 0) return header;
    return header + generateDockerLayers(modules);
}

/**
 * Stage a build context (Dockerfile + module COPY assets) into `dir`.
 * Module copy sources are placed under `modules/<name>/<src>` to match the
 * paths emitted by `generateDockerLayers`.
 */
export function stageBuildContext(
    dir: string,
    baseImage: string,
    modules: ModuleManifest[],
): { dockerfile: string } {
    const dockerfilePath = join(dir, "Dockerfile");
    writeFileSync(dockerfilePath, generateDockerfile(baseImage, modules));

    for (const m of modules) {
        for (const c of m.docker.copy) {
            const moduleRoot = moduleDir(m.name);
            const srcPath = assertInside(moduleRoot, join(moduleRoot, c.src), `copy.src ${c.src}`);
            if (!existsSync(srcPath)) {
                throw new Error(
                    `Module "${m.name}" references missing file "${c.src}".`,
                );
            }
            const destRoot = join(dir, "modules", m.name);
            const destPath = assertInside(destRoot, join(destRoot, c.src), `copy dest ${c.src}`);
            mkdirSync(dirname(destPath), { recursive: true });
            copyFileSync(srcPath, destPath);
        }
    }
    return { dockerfile: dockerfilePath };
}

/** Custom image tag for a given module set. */
export function customImageTag(modules: ModuleManifest[]): string {
    return `1claw-custom-${moduleSetHash(modules)}:latest`;
}

/**
 * Build a module-customized image (FROM base + module layers). Returns the
 * resulting image tag.
 */
export async function buildModuleImage(
    baseImage: string,
    modules: ModuleManifest[],
    onProgress?: (line: string) => void,
): Promise<{ tag: string; contextDir: string }> {
    const tag = customImageTag(modules);
    const dir = mkdtempSync(join(tmpdir(), "1claw-build-"));
    const { dockerfile } = stageBuildContext(dir, baseImage, modules);
    await dockerBuild({ context: dir, dockerfile, tag, onProgress });
    return { tag, contextDir: dir };
}
