# Generated by `1claw deploy --google-cloud`.
# Deploys a 1Claw agent container to Cloud Run with the agent API key stored in
# Secret Manager and injected as an environment variable at runtime.
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 5.0"
    }
  }
}

provider "google" {
  project = var.project_id
  region  = var.region
}

resource "google_secret_manager_secret" "agent_key" {
  secret_id = "${var.service_name}-agent-key"
  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_version" "agent_key" {
  secret      = google_secret_manager_secret.agent_key.id
  secret_data = var.agent_api_key
}

resource "google_cloud_run_v2_service" "agent" {
  name     = var.service_name
  location = var.region

  template {
    containers {
      image = var.image_tag

      ports {
        container_port = 3000
      }

      # Cloud mode: the container talks to the 1Claw API directly using the
      # agent key injected from Secret Manager (no host daemon in the cloud).
      env {
        name  = "ONECLAW_LOCAL_VAULT"
        value = "false"
      }
      env {
        name  = "ONECLAW_AGENT_ID"
        value = var.agent_id
      }
      env {
        name  = "ONECLAW_CONTAINER_MODULES"
        value = var.modules
      }
      env {
        name = "ONECLAW_AGENT_API_KEY"
        value_source {
          secret_key_ref {
            secret  = google_secret_manager_secret.agent_key.secret_id
            version = "latest"
          }
        }
      }
    }
  }
}

resource "google_cloud_run_v2_service_iam_member" "invoker" {
  name     = google_cloud_run_v2_service.agent.name
  location = google_cloud_run_v2_service.agent.location
  role     = "roles/run.invoker"
  member   = var.invoker_member
}
